### ISSUE TITLE
ValueError: didn't find ['img_feat.npy'] in ['__key__', '__url__', 'gen.jpg']

### ISSUE THREAD

**Issue by szulm** [justinpinkney/clip2latent#13]
@justinpinkney hi,I generated 10w data with `generate_dataset.py`, and `ValueError: didn't find ['img_feat.npy'] in ['__key__', '__url__', 'gen.jpg']`appeared in train. Do you know how to solve it

**Comment by szulm** [comment]
have solved!

**Comment by zybYNU** [comment]
Hi! How did you solve this problem? I had a similar problem in train.py. 
ValueError: didn't find ['latent.npy'] in ['__key__', '__url__', 'img_feat.npy']
Do the data generated by generate_dataset.py need to be compressed separately into .tar files?
