### ISSUE TITLE
Setting up PyTorch plugin "bias_act_plugin"... Failed!

### ISSUE THREAD

**Issue by SuperDouble** [justinpinkney/clip2latent#9]
hello, appreciate your open-source work, but I keep getting this problem during the reproduction process despite changing different environment, how can I fix it?

**Comment by SuperDouble** [comment]
have solved!

**Comment by szulm** [comment]
hello！

I also have this problem. How can I solve it？

**Comment by justinpinkney** [comment]
make sure you have ninja installed? `pip install ninja`
